### ISSUE TITLE
Replace subgraph with contract call (It will support batch transactions and all safe versions)

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-relayer#61]
![image](https://user-images.githubusercontent.com/15967809/210072098-41777fd0-2fa2-420d-a643-115853ea7b06.png)
![image](https://user-images.githubusercontent.com/15967809/210072109-239f9116-c49b-459f-b772-152ee75e22cf.png)

**Comment by bonustrack** [comment]
Sound great @ChaituVR
